board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('<int:pk>/new_comment/', views.new_comment),

]

wait_to_the_paradise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('wtp_open.urls')),
    path('wtp/', include('wtp.urls')),
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),

]

wtp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('<int:pk>/', views.wtp_detail),
    path('', views.wtp_list),
    # path('depression', views.Depression.as_view()),
    path('gender', views.Gender.as_view()),
    path('age', views.Age.as_view()),
    path('book', views.Book.as_view()),
    # path('fine', views.Fine.as_view()),
    # path('good', views.Good.as_view()),


]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/board/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/board/{self.pk}'

    def get_content_markdown(self):
        return markdown(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

board/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post', 'author', 'created_at', 'modified_at',)

board/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from django.db.models import Q
from .models import Post, Category, Comment
from .forms import CommentForm


# Create your views here.
class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()

        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context


def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request, 'board/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,

        }
    )


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'category']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            return response

        else:
            return redirect('board/')


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'category']

    template_name = 'board/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()

        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)

        else:
            raise PermissionDenied


def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            return PermissionDenied


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

board/templates/board/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'board/bootstrap/jquery-3.7.0.min.js' %}" media="screen">
    <script src="https://kit.fontawesome.com/2d16194314.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/20f2b02ec6.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>



</head>
<body style="background:url({% static '/board/img/background4.png' %}); background-repeat:no-repeat; background-size:cover; height:100vh;">

<!-- Responsive navbar-->
{% include 'board/navbar.html' %}

<!-- Page content-->
<div class="container my-3">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8 bg-light border-bottom mb-4" id="main-area" style="border-radius:10px;">
            {% block main_area %}
            {% endblock %}
        </div>
        <!-- Side widgets-->
        {% include 'board/side_widgets.html' %}
    </div>
</div>


</body>
</html>

board/templates/board/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>

    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css.map' %}" media="screen">
    <script src="https://kit.fontawesome.com/20f2b02ec6.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'board/bootstrap/main.css' %}">
    <script src="https://kit.fontawesome.com/20f2b02ec6.js" crossorigin="anonymous"></script>
</head>
<body>

<!-- Responsive navbar-->
{% include 'board/navbar.html' %}

<!-- Page content-->
<div class="container my-3">
    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-12 bg-light border-bottom mb-4" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

board/templates/board/comment_form.html
{% extends 'board/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

board/templates/board/navbar.html
{% load socialaccount %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css.map' %}" media="screen">
    <script src="https://kit.fontawesome.com/20f2b02ec6.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'board/bootstrap/main.css' %}">


</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary p-3 text-white" style="background:#BFCAE3; box-shadow: 3px 1px 3px gray;">
    <div class="container">
        <a class="navbar-nav navbar-brand me-auto me-4 " style="color:#FFFFFF; font-family: 'Roboto Slab' , serif; font-size: 1.8rem; text-shadow: 1px 1px 1px gray;" href="/wtp/">Wait to The Paradise</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item px-3"><a class="text-decoration-none icon" style="color:#FFFFFF; font-weight:bold; line-height:40px;" href="/board/">게시판</a></li>
                <li class="nav-item px-3"><a class="text-decoration-none icon" style="color:#FFFFFF; font-weight:bold; line-height:40px;" href="/wtp/">처음으로</a></li>
            </ul>
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {% if user.socialaccount_set.all.0.get_avatar_url %}
                        <img class="rounded-circle" width="25px" src="{{ user.socialaccount_set.all.0.get_
                                avatar_url }}" alt="">
                        {% else %}
                        <img class="rounded-circle" width="40px"
                             src="https://doitdjango.com/avatar/id/1531/97ee52e1a408f085/svg/{{ user.email }}">
                        {% endif %}
                        &nbsp;
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-label="">
                        <li><a class="dropdown-item" href="/accounts/logout/">Log out</a></li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item px-3">
                    <a class="text-decoration-none icon" style="color:#FFFFFF; font-weight:bold; line-height:40px;" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

    <!-- login modal-->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="loginModalLabel" style="color:black">Login</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-content">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-6" style="text-align:center;">
                                <a role="button" class="btn btn-danger btn-w-190" href="{% provider_login_url 'google' %}">
                                    <i class="fa-brands fa-google"></i> Log in with Google</a>
                                <a role="button" class="btn btn-primary btn-w-190" href="/accounts/login/"><i class="fa-sharp fa-regular fa-envelope"></i> Log in with E-mail
                                </a>
                            </div>
                            <div class="col-lg-6" style="text-align:center;">
                                <a role="button" type="button" class="btn btn-warning btn-w-190" href="/accounts/signup/"><i class="far fa-smile-wink"></i> Sign up with E-mail
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer" style="margin-top:10px;">
                        <button type="button" class="btn text-white btn-close-1" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>
</body>

board/templates/board/pagination.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'board/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'board/bootstrap/jquery-3.7.0.min.js' %}" media="screen">
    <script src="https://kit.fontawesome.com/2d16194314.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/20f2b02ec6.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
            integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>

<body>
<!--번호입력하면 이동하는태그-->
<form method="GET" class="d-flex justify-content-center">
    <input type="number" name="page" min="1" max="{{ page_obj.paginator.num_pages }}">
    <input type="submit" value="Go">
</form>
<br/>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 맨 처음 -->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="first">
            <span aria-hidden="true">처음으로</span>
        </a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">처음으로</span>
    </li>
    {% endif %}
    <!-- 이전페이지 -->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:0 and page_number <= page_obj.number|add:10 %}
    {% if page_number == page_obj.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
    <!-- 맨 마지막 -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="last">
            <span aria-hidden="true">끝으로</span>
        </a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">끝으로</span>
    </li>
    {% endif %}
</ul>

<!-- 페이징처리 끝 -->

</body>

board/templates/board/post_detail.html
{% extends 'board/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ post.title }} - 게시판
{% endblock %}

{% block main_area %}
<div id="post-area">
    <!-- Post header-->
    <header class="mb-4">
         Post title
        {% if post.category %}
        <span class="badge text-bg-success float-end mx-8">{{ post.category }}</span>
        {% endif %}
        <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
        <p class="lead">
            by
            <a href="#">{{ post.author | upper }}</a>
        </p>
        <hr/>
        {% if user.is_authenticated and user == post.author %}
        <a class="btn btn-info btn-sm float-right" href="/board/update_post/{{ post.pk }}" role="button">
            <i class="fa-sharp fa-solid fa-pen"></i> Edit Post</a>
        {% endif %}
        <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
        <!-- Post categories-->
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
    </header>
    <!-- Post content-->
    <section class="mb-5">
        <p>{{ post.get_content_markdown | safe}}</p>
    </section>
</div>
<!-- Comments section-->
<div id="comment-area">
    <section class="mb-5">
        <!-- Comment form-->
        <div class="card bg-light">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                {% if user.is_authenticated %}
                <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}/new_comment/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ comment_form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                {% else %}
                <a role="button" class="btn btn-outline-dark btn btn-black btn-sm" href="#"
                   data-bs-toggle="modal" data-bs-target="#loginModal">Log in and leave a comment</a>
                {% endif %}


            {% if post.comment_set.exists %}
                {% for comment in post.comment_set.iterator %}
                <!-- Single comment-->
                <div class="d-flex">
                    <div class="flex-shrink-0" id="comment-{{ comment.pk }}">
                        <img class="rounded-circle" src="{{ comment.get_avatar_url }}"
                             alt="{{ comment.author }}" width="60px">

                        <div class="media-body">
                            {% if user.is_authenticated and comment.author == user %}
                            <div class="float-right">
                                <a role="button"
                                   class="btn btn-sm btn-info"
                                   id="comment-{{ comment.pk }}-update-btn"
                                   href="/board/update_comment/{{ comment.pk }}/">
                                    edit
                                </a>
                                <a role="button"
                                   href="#"
                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                   class="btn btn-sm btn-danger"
                                   data-bs-toggle="modal" data-bs-target="#deleteCommentModal-{{ comment.pk }}">
                                    delete
                                </a>
                            </div>

                            <!--Modal-->
                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1"
                                 role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">정말로 삭제하시나요?</h5>
                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <del>{{ comment | linebreaks }}</del>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                            <a role="button" class="btn btn-danger"
                                               href="/board/delete_comment/{{ comment.pk }}">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            <h5 class="mt-0">{{ comment.author.username }}&nbsp;&nbsp;<small
                                    class="text-muted">{{ comment.created_at }}</small>
                            </h5>
                            <p>{{ comment.content | linebreaks }}</p>
                            {% if comment.created_at != comment.modified_at %}
                            <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}

board/templates/board/post_form.html
{% extends 'board/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Create Post - Blog{% endblock %}

{% block main_area %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

board/templates/board/post_list.html
{% extends 'board/base.html' %}

{% block main_area %}

{% if user.is_authenticated %}
{% if user.is_superuser or user.is_staff %}
<a class="btn btn-info btn-sm float-end" href="/board/create_post/" role="button">
    <i class="fas fa-pen"></i>&nbsp;&nbsp;New Post</a>
{% endif %}
{% endif %}


<h1>
    Blog
    {% if category %}<span class="badge bg-success">{{ category }}</span>{% endif %}
</h1>
{% if post_list.exists %}
{% for p in post_list %}
<!-- Blog post-->
<div class="card mb-4" id="post-{{ p.pk }}">
    <div class="card-body">
        <div class="small text-muted">{{ p.created_at }}</div>
        {% if p.category %}
        <span class="badge text-bg-success float-end">{{ p.category }}</span>
        {% else %}
        <span class="badge text-bg-success float-end">미분류</span>
        {% endif %}
        <h2 class="card-title h4">{{ p.title }}</h2>
        <p class="card-text">{{ p.get_content_markdown | truncatewords_html:10 | safe }}</p>
        <a href="#">{{ p.author | upper }}</a>
        <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read more →</a>
    </div>
</div>
{% endfor %}
{% else %}
<h3>아직 게시물이 없습니다.</h3>
{% endif %}


{% if is_paginated %}
<!-- 페이지네이션 컨텍스트 정의 시작 -->
  {% with page_obj.paginator as paginator %}
    {% include 'board/pagination.html' %}
  {% endwith %}
<!-- 페이지네이션 컨텍스트 정의 끝 -->
{% endif %}
{% endblock %}

board/templates/board/post_update_form.html
{% extends 'board/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Post - Blog{% endblock %}

{% block main_area %}
<h1>Edit Post</h1>
<hr/>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form | crispy }}
    <br/>
    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{% endblock %}

board/templates/board/side_widgets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- Side widgets-->
<div class="col-lg-4 ">
    <!-- Categories widget-->
    <div class="card mb-4 " id="categories-card">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="nb-0">
                        {% for category in categories %}
                        <li>
                            <a class="text-decoration-none" href="{{ category.get_absolute_url }}">
                                {{ category }} ({{ category.post_set.count }})</a>
                        </li>
                        {% endfor %}
                        <li>
                            <a class="text-decoration-none" href="/board/category/no_category/">
                                미분류 ({{ no_category_post_count }})</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>